name: Run Back-End Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (backend)
        working-directory: ./livraback
        run: npm install

      - name: Run tests (backend)
        working-directory: ./livraback
        run: npm test